---
title: "Sunset_Sunrise Calender"
author: "Hilary Parker, modified by Golnaz Jahesh"
date: "`Nov 16, 2015"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The purpose of this package is to create .CSV files , one for sunset times and one for sunrise times
of the user-specifed location. There are 2 functions in this pacakge:

1. `sunset_calc()`  
2. `sunrise_calc()`  

The input parameters are as follow:

'@param date Date at which you want the calendar to start, in yyyy/mm/dd format.  
'#' @param lat  Latitude of location (for sunset time calculation)  
'#' @param long Longitude of location (for sunset time calculation)  
'#' @param timezone Timezone of location (for sunset time calculation).  
'#' @param num.days Number of days you want sunset appointments for.  
'#' @param file Filename for outputted .CSV file (to be uploaded to Google Calendar).  
'#' @param location Location of sunset appointment. Will be input into Google Calendar event as the event location.  


The examples are as follow:

'#' @examples  

'# create_sunset_cal <- function(date= "2015/01/01",  
                                lat = 37.8789,long = -122.5362,  
                                timezone = "UTC-8",file="sunset.csv",  
                                location = "Spruce Harbour Marina,Vancouver, BC V6H")  

`create_sunrise_cal <- function(date="2015/01/01",  
                                lat = 49.2748,timezone = "UTC-8",  
                                num.days = 365,file="sunrise.csv",  
                                location = "Spanish Banks, Vancouver, BC V6T")  


There's a useful tool from Harvard.edu [Here](http://maps.cga.harvard.edu/gpf/)
that finds the user defined[Geographic location](https://en.wikipedia.org/wiki/Location_(geography)).  
